CREATE TABLE all_signals (
    client_trade_id TEXT PRIMARY KEY,
    instrument_name TEXT NOT NULL,
    trade_side TEXT NOT NULL CHECK (trade_side IN ('Long', 'Short', 'Buy', 'Sell')),
    entry_price NUMERIC NOT NULL,
    entry_time TIMESTAMP WITH TIME ZONE NOT NULL,
    exit_price NUMERIC,
    exit_time TIMESTAMP WITH TIME ZONE,
    mae NUMERIC,
    mfe NUMERIC,
    result_ticks NUMERIC,
    trade_duration TEXT,
    take_profit_price NUMERIC,
    stop_loss_price NUMERIC,
    signal TEXT,
    account_name TEXT,
    daily_pnl NUMERIC
);

-- Create an index on instrument_name for faster lookups
CREATE INDEX idx_all_signals_instrument_name ON all_signals(instrument_name);

-- Create an index on entry_time for sorting operations
CREATE INDEX idx_all_signals_entry_time ON all_signals(entry_time);

-- Create an index on account_name for filtering by account
CREATE INDEX idx_all_signals_account_name ON all_signals(account_name);

-- Add comments for better documentation
COMMENT ON TABLE all_signals IS 'Stores all trading signals generated by the system';
COMMENT ON COLUMN all_signals.client_trade_id IS 'Unique identifier for each trade';
COMMENT ON COLUMN all_signals.trade_side IS 'Direction of the trade: Long, Short, Buy, or Sell';
COMMENT ON COLUMN all_signals.entry_time IS 'Time when the signal was entered';
COMMENT ON COLUMN all_signals.exit_time IS 'Time when the signal was exited (null for running signals)';
COMMENT ON COLUMN all_signals.mae IS 'Maximum Adverse Excursion - worst price movement against the position';
COMMENT ON COLUMN all_signals.mfe IS 'Maximum Favorable Excursion - best price movement in favor of the position';
COMMENT ON COLUMN all_signals.account_name IS 'Name of the trading account that generated this signal';
COMMENT ON COLUMN all_signals.daily_pnl IS 'Daily profit and loss for this signal';
